### ISSUE TITLE
[Package]: dependencies of wine

### ISSUE THREAD

**Issue by 500InternalError** [termux-pacman/glibc-packages#121]
### Why is it worth to add this package?

It's actually not a real package request. I managed to build some dependencies of wine, they built successfully on my machine but failed to build on github action. I guess it's kinda improper to directly initiate a PR when there's still problems in a repo, so I initiate this request, just to remind you that you can refer to my repo to port these packages with less pain.

### Source code URL

https://github.com/500InternalError/glibc-packages

### Packaging policy acknowledgement

- [X] I have read the Termux-Pacman [Package Addition Policy](https://github.com/termux-pacman/glibc-packages/wiki/Package-Addition-Policy) and understand that my request will be denied in case of violation.

### Additional information

I haven't tried on device build
No device requirements

**Comment by Maxython** [comment]
Ok, so I understand that you want to add the following packages:
- [ ] fontconfig
- [ ] freetype
- [ ] libdrm
- [ ] libglvnd
- [ ] libpng
- [ ] libx11
- [ ] libxau
- [ ] libxcb
- [ ] libxcomposite
- [ ] libxcursor
- [ ] libxdmcp
- [ ] libxext
- [ ] libxfixes
- [ ] libxi
- [ ] libxinerama
- [ ] libxrandr
- [ ] libxrender
- [ ] libxshmfence
- [ ] libxxf86vm
- [ ] ttf-dejavu
- [ ] vulkan-headers
- [ ] vulkan-loader
- [ ] vulkan-tools
- [ ] xcb-proto
- [ ] xorg-util-macros
- [ ] xorgproto
- [ ] xtrans

I appreciate you providing your fork as a package source, but I noticed that your fork contains copied packages from [termux-packages/x11-packages](https://github.com/termux/termux-packages/tree/master/x11-packages). Which is not correct, since these packages contain patches for the correct operation of bionic, but here the glibc base and these patches can break the packages.

**Comment by 500InternalError** [comment]
> I appreciate you providing your fork as a package source, but I noticed that your fork contains copied packages from [termux-packages/x11-packages](https://github.com/termux/termux-packages/tree/master/x11-packages). Which is not correct, since these packages contain patches for the correct operation of bionic, but here the glibc base and these patches can break the packages.

I know little about the effect of those patches, sorry for that
