### ISSUE TITLE
[enchancment] remove bash and patchelf from deps for glibc-runner

### ISSUE THREAD

**Issue by romanovj** [termux-pacman/glibc-packages#160]
### Problem description

Users can use pacman for glibc packages without switching to pacman. But those dependencies create problems.

installation in fresh termux 
```
yes | pkg upg
pkg i pacman patchelf -y
pacman-key --init
pacman-key --populate
pacman -Syu
pacman -S glibc-runner --assume-installed bash,patchelf --noconfirm
```

suggested packages with and without `--assume-installed bash,patchelf`

![Screenshot_20231112-192222_Termux](https://github.com/termux-pacman/glibc-packages/assets/105647092/4a902711-fc48-4c27-bd0a-2cf26f8d2ad3)

### System information

termux-info:
```
```

**Comment by Maxython** [comment]
This is not a bug and is also not an "improvement". Using the `pacman` package manager in Termux requires a complete transition to it, otherwise a conflict cannot be avoided. And removing `bash` and `patchelf` from `glibc-runner` dependencies can break the package and limit its functionality.

It is worth noting that soon glibc packages will be compiled for the `apt` package manager, that is, there will soon be support for `gpkg` repo for `apt` - https://github.com/termux/glibc-packages
