### ISSUE TITLE
[Question] Can it work with Termux main-repo package?

### ISSUE THREAD

**Issue by hansm629** [termux-pacman/glibc-packages#219]
@Maxython 

hello.
Through Googling, I found out that the glibc package can be used in Termux as well.

bionic libc does not support locales, so multiple languages cannot be used on the XFCE desktop.

So, I have a question.

Can I use glibc-packages together with packages installed from Termux main-repo?

For example, in `XFCE` installed from Termux main-repo:
Is it possible to apply a language other than English through glibc's locale?

The purpose is to:

**1. Apply language as `locale` to the `XFCE desktop environment` installed from `Termux main-repo`.
2. Using `box64` and `wine64` of glibc-packages in the `XFCE desktop environment` installed from `Termux main-repo`
3. Use `vulkan-loader-generic` or `mesa-vulkan-icd-freedreno-dri3` installed from `Termux main-repo` in `box64+wine64 environment`.**

As mentioned above, apply a language other than English to the The purpose is to use it.

Is it possible to use glibc and bionic libc together in this way?

**Comment by Maxython** [comment]
> Can I use glibc-packages together with packages installed from Termux main-repo?
>
> For example, in XFCE installed from Termux main-repo:
> Is it possible to apply a language other than English through glibc's locale?
> 
> Is it possible to use glibc and bionic libc together in this way?

No, it is not possible to make bionic-based binaries use glibc libraries and so that glibc-based binaries use bionic libraries. The libraries use incompatible symbol management strategies, so they cannot be combined. If you want xfce to support the glibc locale, then it must be compiled only on the glibc libraries.

> Using box64 and wine64 of glibc-packages in the XFCE desktop environment installed from Termux main-repo

If you doubt that to run graphical applications based on glibc you need xfce based on glibc, then this is not so. You can safely run them on xfce based on bionic (from the termux main-repo), if the Termux environment itself does not destroy them (roughly speaking, they must be launched in the `glibc-runner` environment).
