### ISSUE TITLE
[Bug]: tcpclient connect segmentation fault

### ISSUE THREAD

**Issue by szllzs** [termux-pacman/glibc-packages#27]
### Problem description

![Screenshot_2023-06-10-09-34-17-65_84d3000e3f4017145260f7618db1d683](https://github.com/termux-pacman/glibc-packages/assets/13085785/09b31a11-a086-4ad0-9778-88f40fdd405a)

server accept is ok,but client connect is bad

### System information

termux-info:
```
```
118

**Comment by Maxython** [comment]
Could you send the `client.c` file?

**Comment by szllzs** [comment]
> Could you send the `client.c` file?

[client.zip](https://github.com/termux-pacman/glibc-packages/files/11711952/client.zip)

**Comment by Maxython** [comment]
This is not a bug in glibc, it's a bug in your code. You just need to uncomment the following lines:
![Screenshot_20230610-115609_Termux](https://github.com/termux-pacman/glibc-packages/assets/60917834/ca35701e-e61e-4241-90be-2001dfdf9359)

PS: next time, be sure that some error is due to glibc (or because of the glibc packages)

**Comment by szllzs** [comment]
> This is not a bug in glibc, it's a bug in your code. You just need to uncomment the following lines: ![Screenshot_20230610-115609_Termux](https://user-images.githubusercontent.com/60917834/244860673-ca35701e-e61e-4241-90be-2001dfdf9359.jpg)
> 
> PS: next time, be sure that some error is due to glibc (or because of the glibc packages)

I see, it was my negligence, thank you very much
