### ISSUE TITLE
Do you have roadmap?

### ISSUE THREAD

**Issue by romanovj** [termux-pacman/glibc-packages#74]

**Comment by Maxython** [comment]
What do you mean by "roadmap"?

**Comment by romanovj** [comment]
which steps should be taken in order to create  fully functional stand alone glibc termux

**Comment by Maxython** [comment]
> which steps should be taken in order to create fully functional stand alone glibc termux

I understand that by `glibc termux` you mean bootstrap for Termux based on glibc. If so, then for `fully functional stand alone` requires standard linux packages (eg: bash, pacman, util-linux, and so on) to be compiled against glibc for Termux. It also requires a package service that will provide updates to such packages or provide new ones. It's worth noting that I don't have any plans to build Termux bootstrap based on glibc, as the glibc packages are meant to be used in regular Termux bootstrap.  But that doesn't mean there won't be resources to build bootstrap based on glibc in the future.

If I misunderstood you, then ask your question in detail so that I immediately understand.

**Comment by romanovj** [comment]
I just compiled box64 with glibc gcc in termux, imported missing arm64 libs from debian bookworm and able to start notepad and some others apps without proot/root. It would be good to have natively compiled packages.

**Comment by Maxython** [comment]
> I just compiled box64 with glibc gcc in termux, imported missing arm64 libs from debian bookworm and able to start notepad and some others apps without proot/root. It would be good to have natively compiled packages.

Now I fully understand you. Yes, I am developing a `gpkg` repo where the main idea is that users will be able to add or request new packages.
